config/routes.rb
Ride2::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :places
  resources :tags

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/places_tags_join_table.rb
class PlacesTagsJoinTable < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params[:place]
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params[:tag]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= "Ride2.ru | Welcome" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
	<%= stylesheet_link_tag    "application"%>
	<%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
    
    <!--Google maps API linl-->
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCsbzuJDUEOoq-jS1HO-LUXW4qo0gW9FNs&sensor=false"></script>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]> <script src="../../assets/js/html5shiv.js"></script> <script src="../../assets/js/respond.min.js"></script> <![endif]-->
</head>
<body onload="initialize()">

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<!--autorization modal-->
    <div class="modal fade" id="autorization">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Авторизация</h4>
                </div>
                <div class="modal-body">
                    <form role="form">
                        <div class="form-group">
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="почта" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="пароль" />
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" />
                                чужой компьютер
                            </label>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <p><a href="1.html" class="btn btn-danger btn-sm">Войти</a></p>
                    <p><a href="1.html" class="btn btn-primary btn-sm">Зарегистрироваться</a></p>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!--map-->
    <div id="map_canvas" class="map"></div>
    <!--/map-->
    <div class="row site">
        <div class="col-md-1 general_menu startpage">
            <ul>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-chef"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-football-soccer"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-controllerps"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-leaf"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-shopping"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-student-school"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-wine"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-wallet"></i></a>
                </li>
                <li>
                    <a href="#" class="gradientmenu"><i class="icon-bus"></i></a>
                </li>
            </ul>
        </div>
        <!--Content-->
        <div class="col-md-11 general_content_styles index_content" id="cont">
            <!--Header-->
            <div class="row">
                <div class="col-md-12 header">
                    <div class="logo">
                        <a href="#">
                            <img src="/images/logo.png" alt="..."/></a>
                    </div>
                    <div class="autorization_btn"><a data-toggle="modal" href="#autorization" class="btn btn-danger btn-sm">Зарегистрироваться</a></div>
                </div>
            </div>
            <!--/Header-->
                 <!--Map open (for adaptive)-->
            <div class="row map_open">
                <div class="col-md-12">
                    <a href="#" id="map_open">Открыть карту</a>
                </div>
            </div>
              <!--/Map open (for adaptive)-->
            <!--search-->
            <div class="row">
                <div class="col-md-12">
                    <div class="row search_block">
                        <div class="text_in_search">Найди новые места для отдыха</div>
                        <div class="search">
                            <input type="text" class="form-control  input-sm" id="exampleInputEmail2" placeholder="Укажи почту" />
                        </div>
                        <a href="4.html" class="btn btn-warning col-md-2 btn-sm">Найти</a>
                    </div>
                </div>
            </div>
            <!--/search-->
            <!--Features-->
            <div class="row features">
                <div class="col-md-6">
                    <h4><i class="icon-groups-friends"></i>Узнать историю</h4>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
                </div>
                <div class="col-md-6">
                    <h4><i class="icon-thumbs-up"></i>Сделать крутую фотосессию</h4>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
                </div>
                <div class="col-md-6">
                    <h4><i class="icon-automobile-car"></i>Отдохнуть кампанией</h4>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
                </div>
                <div class="col-md-6">
                    <h4><i class="icon-addfriend"></i>Открыть что нибудь новое</h4>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
                </div>
            </div>
            <!--/Features-->
            <!--tooltip-->
            <div class="jumbotron">
                <div class="container">
                    <h2>Нас уже 1 000 000 человек!</h2>
                    <p><a class="btn btn-danger btn-sm">Подробнее</a></p>
                </div>
            </div>
            <!--/tooltip-->
            <!--places-->
            <h3>Лучшие места за сегодня</h3>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                        <!--place-->
                        <div class="col-sm-6 col-md-4 places">
                            <div class="thumbnail">
                                <img src="img/demo01.png" alt="..." />
                                <div class="caption">
                                    <a href="3.html">Thumbnail label</a>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem </p>
                                    <p>
                                        <img src="img/start.gif" alt="..."/>
                                        <a href="3.html" class="btn btn-default btn-xs"><i class="icon-user"></i>87</a><a href="#" class="btn btn-default btn-xs"><i class="icon-commentround"></i>12</a><a href="#" class="btn btn-default btn-xs ping"><i class="icon-map-marker"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!--/place-->
                    </div>
                </div>
            </div>
            <!--/places-->
        </div>
        <!--/Content-->
    </div>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>